apiVersion: v1
kind: List
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: cas.fabric.hyperledger.org
  spec:
    group: fabric.hyperledger.org
    names:
      kind: CA
      listKind: CAList
      plural: cas
      singular: ca
    scope: Namespaced
    subresources:
      status: {}
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              admin:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
              adminPassword:
                type: string
              certs:
                properties:
                  cert:
                    type: string
                  key:
                    type: string
                  tlsCert:
                    type: string
                  tlsKey:
                    type: string
                type: object
              nodeSpec:
                properties:
                  configParams:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  hosts:
                    items:
                      type: string
                    type: array
                  image:
                    type: string
                  resources:
                    type: object
                  storageClass:
                    type: string
                  storageSize:
                    type: string
                required:
                - image
                - configParams
                type: object
            required:
            - admin
            - adminPassword
            type: object
          status:
            properties:
              accessPoint:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "operator-sdk generate k8s" to regenerate
                  code after modifying this file Add custom validation using kubebuilder
                  tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
            required:
            - accessPoint
            type: object
    versions:
    - name: v1alpha1
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: peers.fabric.hyperledger.org
  spec:
    group: fabric.hyperledger.org
    names:
      kind: Peer
      listKind: PeerList
      plural: peers
      singular: peer
    scope: Namespaced
    subresources:
      status: {}
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              msp:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                properties:
                  adminCerts:
                    description: Administrator's certificates
                    items:
                      type: string
                    type: array
                  caCerts:
                    description: CA certificates
                    items:
                      type: string
                    type: array
                  keyStore:
                    description: node private key
                    type: string
                  signCerts:
                    description: node certificate
                    type: string
                  tlsCacerts:
                    description: ca tls certificates
                    items:
                      type: string
                    type: array
                required:
                - adminCerts
                - caCerts
                - keyStore
                - signCerts
                type: object
              nodeSpec:
                properties:
                  configParams:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  hosts:
                    items:
                      type: string
                    type: array
                  image:
                    type: string
                  resources:
                    type: object
                  storageClass:
                    type: string
                  storageSize:
                    type: string
                required:
                - image
                - configParams
                type: object
              tls:
                properties:
                  tlsCert:
                    description: node certificate
                    type: string
                  tlsKey:
                    description: node private key
                    type: string
                required:
                - tlsCert
                - tlsKey
                type: object
            required:
            - msp
            - tls
            type: object
          status:
            properties:
              accessPoint:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "operator-sdk generate k8s" to regenerate
                  code after modifying this file Add custom validation using kubebuilder
                  tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
            required:
            - accessPoint
            type: object
        required:
        - spec
    versions:
    - name: v1alpha1
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: orderers.fabric.hyperledger.org
  spec:
    group: fabric.hyperledger.org
    names:
      kind: Orderer
      listKind: OrdererList
      plural: orderers
      singular: orderer
    scope: Namespaced
    subresources:
      status: {}
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              msp:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                properties:
                  adminCerts:
                    description: Administrator's certificates
                    items:
                      type: string
                    type: array
                  caCerts:
                    description: CA certificates
                    items:
                      type: string
                    type: array
                  keyStore:
                    description: node private key
                    type: string
                  signCerts:
                    description: node certificate
                    type: string
                  tlsCacerts:
                    description: ca tls certificates
                    items:
                      type: string
                    type: array
                required:
                - adminCerts
                - caCerts
                - keyStore
                - signCerts
                type: object
              nodeSpec:
                properties:
                  configParams:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  hosts:
                    items:
                      type: string
                    type: array
                  image:
                    type: string
                  resources:
                    type: object
                  storageClass:
                    type: string
                  storageSize:
                    type: string
                required:
                - image
                - configParams
                type: object
              tls:
                properties:
                  tlsCert:
                    description: node certificate
                    type: string
                  tlsKey:
                    description: node private key
                    type: string
                required:
                - tlsCert
                - tlsKey
                type: object
            required:
            - msp
            - tls
            type: object
          status:
            properties:
              accessPoint:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "operator-sdk generate k8s" to regenerate
                  code after modifying this file Add custom validation using kubebuilder
                  tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
            required:
            - accessPoint
            type: object
        required:
        - spec
    versions:
    - name: v1alpha1
      served: true
      storage: true
  