parameters:
  param: []

jobs:
- ${{ each component in parameters.param }}:
  - job: ${{ component.name }}
    steps:
    - template: check-component.yml
      parameters:
        componentName: ${{ component.name }}
    - ${{ if component.pretest }}:
      - ${{ if eq(variables['ContinueJob'], 'True') }}:
        - template: ${{ component.pretest }}
    - ${{ each image in component.images }}:
      - script: |
          docker build -t ${{ image.imagename }} -f ${{ image.dockerfile }} .
        displayName: Build ${{ image.imagename }} docker image
        condition: eq(variables['ContinueJob'], 'True')
      - script: docker images
        displayName: 'List available images'
        condition: eq(variables['ContinueJob'], 'True')
    - ${{ if component.posttest }}:
      - ${{ if eq(variables['ContinueJob'], 'True') }}:
        - template: ${{ component.posttest }}
    - ${{ each image in component.images }}:
      - script: |
          docker login --username $(DockerHub-Username) --password $(DockerHub-Password)
          docker push ${{ image.imagename }}
        displayName: Publish docker image ${{ image.imagename }}
        condition: and(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['ContinueJob'], 'True'))
